'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''


def fibonnaci_q():

    number = 0
    new_number = 1

    fibonnaci_sequence = []

    fibonacci_no = 0



    for i in range(5000000):

           if fibonacci_no > 4000000:
               break
           else:

               fibonacci_no = new_number + number
               number = new_number
               new_number = fibonacci_no
               fibonnaci_sequence.append(fibonacci_no)
               #print(fibonnaci_sequence)

    print(fibonnaci_sequence)
    even_sum = 0

    for terms in fibonnaci_sequence:
        if terms%2 == 0:
            even_sum = even_sum + terms


    print(even_sum)

fibonnaci_q()